name: test

on:
  push:
  pull_request:
  workflow_dispatch:  # allows manual triggering

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies from pyproject.toml
        run: |
          python -m pip install --upgrade pip
          pip uninstall -y tensorflow keras || true
          pip install "tensorflow<2.15"
          pip install --no-cache-dir --force-reinstall .[test]
          pip install pytest  # fallback

      - name: Run tests with pytest
        run: pytest

      - name: Show TensorFlow and NumPy versions
        run: python -c "import tensorflow as tf, numpy as np; print('TF:', tf.__version__, '| NumPy:', np.__version__)"
